apiVersion: v1
entries:
  strimzi-kafka-operator:
  - apiVersion: v2
    appVersion: 0.49.1
    created: "2025-12-06T10:28:20.570056+01:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: f36ffbd4dd5c27e34f4c7445e9df5b905fd27ad34e7ff05826cb44d4d8da4e43
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - email: cncf-strimzi-maintainers@lists.cncf.io
      name: Strimzi Project Maintainers
      url: https://github.com/strimzi/governance
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.49.1.tgz
    version: 0.49.1
  - apiVersion: v2
    appVersion: 0.49.0
    created: "2025-12-06T10:28:20.564522+01:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: 62e5f1543d5cc715f8a80c7850974d2df1b524478271f52d6662d582ceef262d
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - email: cncf-strimzi-maintainers@lists.cncf.io
      name: Strimzi Project Maintainers
      url: https://github.com/strimzi/governance
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.49.0.tgz
    version: 0.49.0
  - apiVersion: v2
    appVersion: 0.48.0
    created: "2025-12-06T10:28:20.560427+01:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: 158ae5d1a72fa01fbef8e070d2531e75c5aa321d26bb149c59b771e9380cbff0
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - email: cncf-strimzi-maintainers@lists.cncf.io
      name: Strimzi Project Maintainers
      url: https://github.com/strimzi/governance
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.48.0.tgz
    version: 0.48.0
  - apiVersion: v2
    appVersion: 0.47.0
    created: "2025-12-06T10:28:20.557249+01:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: 3907c0b2638ba59ef8a1bad7ed218dd0f6e7205569d3051983bcdf8aea202913
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - email: cncf-strimzi-maintainers@lists.cncf.io
      name: Strimzi Project Maintainers
      url: https://github.com/strimzi/governance
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.47.0.tgz
    version: 0.47.0
  - apiVersion: v2
    appVersion: 0.46.1
    created: "2025-12-06T10:28:20.553684+01:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: 911a92445ca3821b04694b3dba29625ac96796e11a31b7b802111cd1103778db
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - name: Frawless
    - name: ppatierno
    - name: samuel-hawker
    - name: scholzj
    - name: tombentley
    - name: sknot-rh
    - name: PaulRMellor
    - name: im-konge
    - name: see-quick
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.46.1.tgz
    version: 0.46.1
  - apiVersion: v2
    appVersion: 0.46.0
    created: "2025-12-06T10:28:20.550206+01:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: 4ced19860a2a044c1fac0b8009ffc2678b53ff0799bf95fd94ac6e397a6dda73
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - name: Frawless
    - name: ppatierno
    - name: samuel-hawker
    - name: scholzj
    - name: tombentley
    - name: sknot-rh
    - name: PaulRMellor
    - name: im-konge
    - name: see-quick
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.46.0.tgz
    version: 0.46.0
  - apiVersion: v2
    appVersion: 0.45.1
    created: "2025-12-06T10:28:20.546894+01:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: beec7586292b30fc446796801393fb9ac8db75b1bd4a5c1484964708b9e270f2
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - name: Frawless
    - name: ppatierno
    - name: samuel-hawker
    - name: scholzj
    - name: tombentley
    - name: sknot-rh
    - name: PaulRMellor
    - name: im-konge
    - name: see-quick
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.45.1.tgz
    version: 0.45.1
  - apiVersion: v2
    appVersion: 0.45.0
    created: "2025-12-06T10:28:20.543248+01:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: 1e406e60b0dc2e66555f6c1080c07ae047efbffef6a06f169c46139dd02e0bc7
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - name: Frawless
    - name: ppatierno
    - name: samuel-hawker
    - name: scholzj
    - name: tombentley
    - name: sknot-rh
    - name: PaulRMellor
    - name: im-konge
    - name: see-quick
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.45.0.tgz
    version: 0.45.0
  - apiVersion: v2
    appVersion: 0.44.0
    created: "2025-12-06T10:28:20.540127+01:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: ea827095480b585cf00b7ce94ef3146e6a83e79459dd3bd65da4464e3b13e14e
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - name: Frawless
    - name: ppatierno
    - name: samuel-hawker
    - name: scholzj
    - name: tombentley
    - name: sknot-rh
    - name: PaulRMellor
    - name: im-konge
    - name: see-quick
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.44.0.tgz
    version: 0.44.0
  - apiVersion: v2
    appVersion: 0.43.0
    created: "2025-12-06T10:28:20.536674+01:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: 36b48f8ec692e47bf478b81b8e208012a3c981d19cb83ac04376ab2cb2120802
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - name: Frawless
    - name: ppatierno
    - name: samuel-hawker
    - name: scholzj
    - name: tombentley
    - name: sknot-rh
    - name: PaulRMellor
    - name: im-konge
    - name: see-quick
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.43.0.tgz
    version: 0.43.0
  - apiVersion: v2
    appVersion: 0.42.0
    created: "2025-12-06T10:28:20.533246+01:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: b4c624ad071149787d94cd782b739df22fe8db7b596d46863557d39177abd025
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - name: Frawless
    - name: ppatierno
    - name: samuel-hawker
    - name: scholzj
    - name: tombentley
    - name: sknot-rh
    - name: PaulRMellor
    - name: im-konge
    - name: see-quick
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.42.0.tgz
    version: 0.42.0
generated: "2025-12-06T10:28:20.52996+01:00"
