apiVersion: v1
entries:
  strimzi-kafka-operator:
  - apiVersion: v2
    appVersion: 0.49.0
    created: "2025-11-26T19:43:10.542227+01:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: 62e5f1543d5cc715f8a80c7850974d2df1b524478271f52d6662d582ceef262d
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - email: cncf-strimzi-maintainers@lists.cncf.io
      name: Strimzi Project Maintainers
      url: https://github.com/strimzi/governance
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.49.0.tgz
    version: 0.49.0
  - apiVersion: v2
    appVersion: 0.48.0
    created: "2025-11-26T19:43:10.535167+01:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: 158ae5d1a72fa01fbef8e070d2531e75c5aa321d26bb149c59b771e9380cbff0
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - email: cncf-strimzi-maintainers@lists.cncf.io
      name: Strimzi Project Maintainers
      url: https://github.com/strimzi/governance
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.48.0.tgz
    version: 0.48.0
generated: "2025-11-26T19:43:10.531559+01:00"
