apiVersion: v1
entries:
  nats:
  - apiVersion: v2
    appVersion: 2.10.24
    created: "2024-12-28T22:04:28.909753+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: 57fd89bf7b55e52650dfdc5986a711d0eb70f585bbbd61fa418f55d1d3ecbd9e
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.2.8.tgz
    version: 1.2.8
  - apiVersion: v2
    appVersion: 2.10.23
    created: "2024-12-28T22:04:28.903828+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: bc8d7703e8569adcdca8e9e0612c150337ebca74a369df47d9ea334cea886c23
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.2.7.tgz
    version: 1.2.7
  - apiVersion: v2
    appVersion: 2.10.22
    created: "2024-12-28T22:04:28.89814+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: 0502fd4922a7fbbd865784f93b6470c65d30287593990c1742656a87992b1dca
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.2.6.tgz
    version: 1.2.6
  - apiVersion: v2
    appVersion: 2.10.21
    created: "2024-12-28T22:04:28.891249+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: e59062a2810b4cdfcd71078aaee89651f0ea875c8beed0a0f26ff7c08c2a9a5f
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.2.5.tgz
    version: 1.2.5
  - apiVersion: v2
    appVersion: 2.10.20
    created: "2024-12-28T22:04:28.882972+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: 360fff97d7ea8b4a77bf5c00bc5e50ab60a00117f9429b2925d8a09fb689081a
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.2.4.tgz
    version: 1.2.4
  - apiVersion: v2
    appVersion: 2.10.19
    created: "2024-12-28T22:04:28.876343+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: aeb6db50fc50d918ce9c76a2f0c3870926815785f926e43e9f51d10a6138f433
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.2.3.tgz
    version: 1.2.3
  - apiVersion: v2
    appVersion: 2.10.18
    created: "2024-12-28T22:04:28.870405+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: 8b66f4656aaa330aaee992eff66f912dfbc7aefd60bb65d0114d5723a5858c7e
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.2.2.tgz
    version: 1.2.2
  - apiVersion: v2
    appVersion: 2.10.17
    created: "2024-12-28T22:04:28.863383+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: b35d6fba525e98dc0b0f060929b600bb60ce699a34623682a82c9fb449e14a2c
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v2
    appVersion: 2.10.16
    created: "2024-12-28T22:04:28.857766+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: ac1863c766e70130c90ec55f6ad35a4d5dbe854639ff598806a15b12181c2634
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 2.10.16
    created: "2024-12-28T22:04:28.811196+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: 75e4a40d905e2eb42f88bfb46a0bfd5f4367231cf29dadcd8df905b8b2f3b881
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.1.12.tgz
    version: 1.1.12
  - apiVersion: v2
    appVersion: 2.10.14
    created: "2024-12-28T22:04:28.805351+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: 4ca7414a633663435ba1d7488e45b289e54536404b89ddc8db51b43ef6d2a1a8
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.1.11.tgz
    version: 1.1.11
  - apiVersion: v2
    appVersion: 2.10.12
    created: "2024-12-28T22:04:28.798294+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: 88fa1d9b682ff98a4394b8e6f8bc86b2c0a7015600bddec6250b28ffb536e521
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.1.10.tgz
    version: 1.1.10
  - apiVersion: v2
    appVersion: 2.10.11
    created: "2024-12-28T22:04:28.851844+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: be6a9a7c7bb670e40c44a7d94dbf5c5a19f5f3be0c60f3b5e9a6b5de155aa58d
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.1.9.tgz
    version: 1.1.9
  - apiVersion: v2
    appVersion: 2.10.10
    created: "2024-12-28T22:04:28.847258+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: b5108f2eaa884d3e675f5a0340e1002108c3b66b05c01a07b895c6b729c45f4a
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.1.8.tgz
    version: 1.1.8
  - apiVersion: v2
    appVersion: 2.10.9
    created: "2024-12-28T22:04:28.842906+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: ec593d1c7667435149cfd6399cb5edfe6e38fcb642660277871c5c29f483881c
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.1.7.tgz
    version: 1.1.7
  - apiVersion: v2
    appVersion: 2.10.7
    created: "2024-12-28T22:04:28.838188+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: 506c2f33bfb822aaf41e916e7a2cee92c29a7c1260675878e370867c708bacd9
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.1.6.tgz
    version: 1.1.6
  - apiVersion: v2
    appVersion: 2.10.5
    created: "2024-12-28T22:04:28.832304+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: e751463a9381c83fd75340e6f7ab996b1fac05d04e6596aab3cdbd6b527becc2
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.1.5.tgz
    version: 1.1.5
  - apiVersion: v2
    appVersion: 2.10.4
    created: "2024-12-28T22:04:28.827502+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: b08c38a7e6b376a32f7de39c9ccd939fa5ef81e6681049c60fbf3ccb0607aa57
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.1.4.tgz
    version: 1.1.4
  - apiVersion: v2
    appVersion: 2.10.4
    created: "2024-12-28T22:04:28.821846+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: b0eb6e97636e87fc84184d63570f1f161891f6e157fcc772ee9deea645fc9877
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.1.3.tgz
    version: 1.1.3
  - apiVersion: v2
    appVersion: 2.10.3
    created: "2024-12-28T22:04:28.816517+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: 20c252dc64d1019d3086c8a76ca82ade3770ac9df76431667c38307e210bab63
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.1.2.tgz
    version: 1.1.2
  - apiVersion: v2
    appVersion: 2.10.2
    created: "2024-12-28T22:04:28.790117+01:00"
    description: A Helm chart for the NATS.io High Speed Cloud Native Distributed
      Communications Technology.
    digest: e64d1fb0002f05e78f35f30a013714afb751c10433a3a6b3d98c59e1b05cfe6d
    home: http://github.com/nats-io/k8s
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - nats
    - messaging
    - cncf
    maintainers:
    - email: info@nats.io
      name: The NATS Authors
      url: https://github.com/nats-io
    name: nats
    urls:
    - nats-1.1.1.tgz
    version: 1.1.1
  nats-operator:
  - apiVersion: v2
    appVersion: 0.8.3
    created: "2024-12-28T22:04:28.920126+01:00"
    description: NATS operator creates/configures/manages nats clusters atop Kubernetes
    digest: 60cc2413675f8e22f4ca46f50fe103d76e4a3cb22ffdbefd52ca02e31707558c
    home: https://github.com/nats-io/nats-operator
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - addressing
    - discovery
    - messaging
    - nats
    - operator
    - pubsub
    maintainers:
    - email: richerlariviere@gmail.com
      name: richerlariviere
    - email: wally@nats.io
      name: Waldemar Quevedo
      url: https://github.com/wallyqs
    name: nats-operator
    sources:
    - https://github.com/nats-io/nats-operator
    urls:
    - nats-operator-0.8.3.tgz
    version: 0.8.3
  - apiVersion: v2
    appVersion: 0.7.4
    created: "2024-12-28T22:04:28.91561+01:00"
    description: NATS operator creates/configures/manages nats clusters atop Kubernetes
    digest: 2e83d6d8c5681e97c65a7b8e6d2870135c25f2c35f8f3795fd517b233c48d3d8
    home: https://github.com/nats-io/nats-operator
    icon: https://nats.io/img/nats-icon-color.png
    keywords:
    - addressing
    - discovery
    - messaging
    - nats
    - operator
    - pubsub
    maintainers:
    - email: richerlariviere@gmail.com
      name: richerlariviere
    - email: wally@nats.io
      name: Waldemar Quevedo
    - email: jaime@nats.io
      name: Jaime Pi√±a
    name: nats-operator
    sources:
    - https://github.com/nats-io/nats-operator
    urls:
    - nats-operator-0.7.4.tgz
    version: 0.7.4
generated: "2024-12-28T22:04:28.779065+01:00"
