apiVersion: v1
entries:
  secrets-store-csi-driver:
  - apiVersion: v2
    appVersion: 1.5.4
    created: "2025-12-03T02:09:31.102828+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: b718bff0882e1211ebd5e242dff7b5f9c527eb677f169636f5d0ecca488d8654
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.5.4.tgz
    version: 1.5.4
  - apiVersion: v2
    appVersion: 1.5.3
    created: "2025-12-03T02:09:31.102012+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 1c1ef51233af6d9c89d95319e45afa4f7835c38bb2f34ffdaec919e125094876
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.5.3.tgz
    version: 1.5.3
  - apiVersion: v2
    appVersion: 1.5.2
    created: "2025-12-03T02:09:31.100977+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 1a224d8df100b08eaf576211ed4c6ac6eeb1444e27a1772c2c60105e7a06435b
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.5.2.tgz
    version: 1.5.2
  - apiVersion: v2
    appVersion: 1.5.1
    created: "2025-12-03T02:09:31.100201+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 809cc8406631326413596eb5aa0129697091ca5aec0ad24baebe0484890380fb
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.5.1.tgz
    version: 1.5.1
  - apiVersion: v2
    appVersion: 1.5.0
    created: "2025-12-03T02:09:31.099395+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: bb4afbc4ece5182b31f8751c5f47319bc7ce0530456b391b4aa58e7d4faae127
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.5.0.tgz
    version: 1.5.0
  - apiVersion: v2
    appVersion: 1.4.8
    created: "2025-12-03T02:09:31.098616+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 894ee5351f615184af4ad0f4ea03be35485e65bc1797c10e315fcd1bcc3aef13
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.4.8.tgz
    version: 1.4.8
  - apiVersion: v2
    appVersion: 1.4.7
    created: "2025-12-03T02:09:31.097706+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: cadee11efe59ebb8c18a64b61fd80abe44a8ed7dd34a149d7bec87bd0e775065
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.4.7.tgz
    version: 1.4.7
  - apiVersion: v2
    appVersion: 1.4.6
    created: "2025-12-03T02:09:31.096603+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 0f04d428f14e6706e2c6f4fe73111e64faa2f551cb7c17a28b8701f2c575233a
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.4.6.tgz
    version: 1.4.6
  - apiVersion: v2
    appVersion: 1.4.5
    created: "2025-12-03T02:09:31.095766+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 75f12e2cd9633921baf49f8044cf5d46de1673aca532c5997a54ce19765761f3
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.4.5.tgz
    version: 1.4.5
  - apiVersion: v2
    appVersion: 1.4.4
    created: "2025-12-03T02:09:31.094908+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: d9a84681d5162f131562324e7f0c3e30b9972f5a046ada0281633cb733d18e0d
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.4.4.tgz
    version: 1.4.4
  - apiVersion: v2
    appVersion: 1.4.3
    created: "2025-12-03T02:09:31.094097+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 6aa4672d0e1521d847a2d2e0f51037562bd3d31c2881f8c84743411484f5ce85
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.4.3.tgz
    version: 1.4.3
  - apiVersion: v2
    appVersion: 1.4.2
    created: "2025-12-03T02:09:31.093151+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 2b602ee40e7b908413566abdaf37ae3fbae13a208588d9384aebb80fbd2f44fa
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.4.2.tgz
    version: 1.4.2
  - apiVersion: v2
    appVersion: 1.4.1
    created: "2025-12-03T02:09:31.092427+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 7507ade5959d1e140fce45c931f09f1b1718b6c69ee6715aade9c43aa7a7cd30
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.4.1.tgz
    version: 1.4.1
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2025-12-03T02:09:31.091396+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: b72e97790bf9e7b9781f3bd92232572e77693afe60a886435681b1d2f2345c61
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.4.0.tgz
    version: 1.4.0
  - apiVersion: v2
    appVersion: 1.3.4
    created: "2025-12-03T02:09:31.090701+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: 253936c7a6812c398e01c967318ff39e3d0f55fa564b2476330796d906af5bc0
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.3.4.tgz
    version: 1.3.4
  - apiVersion: v2
    appVersion: 1.3.3
    created: "2025-12-03T02:09:31.089977+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: c47498bbba1e82490d040500fb9b9e3667c71d327cd0d1b7d89a53535edccefd
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.3.3.tgz
    version: 1.3.3
  - apiVersion: v2
    appVersion: 1.3.2
    created: "2025-12-03T02:09:31.089062+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: c3f9608b705da370ef858f2e8157b869296b77d06db569ad45b9c4a29921f7a2
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.3.2.tgz
    version: 1.3.2
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2025-12-03T02:09:31.087889+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: ad4f5d68e4a7e2fdbc8165fad3fc74f727130e097a79625b73d96d9075df1b19
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.3.1.tgz
    version: 1.3.1
  - apiVersion: v2
    appVersion: 1.3.0
    created: "2025-12-03T02:09:31.086823+01:00"
    description: A Helm chart to install the SecretsStore CSI Driver inside a Kubernetes
      cluster.
    digest: cc05e3f82a957ca39df27205e956efaf1d36eb8b69b44916b319b6c16517a30a
    icon: https://github.com/kubernetes/kubernetes/blob/master/logo/logo.png
    kubeVersion: '>=1.16.0-0'
    maintainers:
    - email: ritazh@microsoft.com
      name: Rita Zhang
    name: secrets-store-csi-driver
    sources:
    - https://github.com/kubernetes-sigs/secrets-store-csi-driver
    urls:
    - secrets-store-csi-driver-1.3.0.tgz
    version: 1.3.0
generated: "2025-12-03T02:09:31.085785+01:00"
