apiVersion: v1
entries:
  ingress-nginx:
  - annotations:
      artifacthub.io/changes: |
        - Update Ingress-Nginx version controller-v1.14.0
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.14.0
    created: "2025-12-05T08:20:47.02286+01:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: d35423da562d1ab66c17feb11374c1c5f4c28c67d77541035deb9dd3023f01e7
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.14.0.tgz
    version: 4.14.0
  - annotations:
      artifacthub.io/changes: |
        - Update Ingress-Nginx version controller-v1.13.4
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.13.4
    created: "2025-12-05T08:20:47.015371+01:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: e5a5847c25479c3e672ca6acba9979c328a2a2ba0e9cc3952d27fe4baf370681
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.13.4.tgz
    version: 4.13.4
  - annotations:
      artifacthub.io/changes: |
        - Update Ingress-Nginx version controller-v1.13.3
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.13.3
    created: "2025-12-05T08:20:47.007231+01:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 616437d8121bd8b558bd3651c00ded094649235f714f0a6980fbb76bf5ba59b0
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.13.3.tgz
    version: 4.13.3
  - annotations:
      artifacthub.io/changes: |
        - Update Ingress-Nginx version controller-v1.13.2
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.13.2
    created: "2025-12-05T08:20:46.999877+01:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: e6b654094435005e8605afaf51b928def3218a767bb6c9c90b9a7f2622a5953a
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.13.2.tgz
    version: 4.13.2
  - annotations:
      artifacthub.io/changes: |
        - 'Make: Add `helm-test` target. (#13659)'
        - Update Ingress-Nginx version controller-v1.13.1
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.13.1
    created: "2025-12-05T08:20:46.99205+01:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: d455dcb35f7c9e1d28efde0d57c639d6db04c6932da8b1fe2bc48ccc0a3d1187
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.13.1.tgz
    version: 4.13.1
  - annotations:
      artifacthub.io/changes: |
        - Update Ingress-Nginx version controller-v1.13.0
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.13.0
    created: "2025-12-05T08:20:46.98472+01:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 73c9231dc3abf69f98af02ea8a1eaaaa2cde3e53aa775eb1c5bcf79b0d4f9f78
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.13.0.tgz
    version: 4.13.0
  - annotations:
      artifacthub.io/changes: |
        - Update Ingress-Nginx version controller-v1.12.8
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.12.8
    created: "2025-12-05T08:20:46.97664+01:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 1015d44a706acf862659386cd41807eaa1dee786954f2c2e74bda84a52f4bc12
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.12.8.tgz
    version: 4.12.8
  - annotations:
      artifacthub.io/changes: |
        - Update Ingress-Nginx version controller-v1.12.7
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.12.7
    created: "2025-12-05T08:20:46.96818+01:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 19cb18c770e174969f79c0938e5fa4b803cc17f8d337347fc5efad7915ebe46e
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.12.7.tgz
    version: 4.12.7
  - annotations:
      artifacthub.io/changes: |
        - Update Ingress-Nginx version controller-v1.12.6
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.12.6
    created: "2025-12-05T08:20:46.961151+01:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 89de6e20c5c7acc037d4b34d5cabda9b1dcae833d9f54083962a230fd5a6026a
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.12.6.tgz
    version: 4.12.6
  - annotations:
      artifacthub.io/changes: |
        - 'Make: Add `helm-test` target. (#13660)'
        - Update Ingress-Nginx version controller-v1.12.5
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.12.5
    created: "2025-12-05T08:20:46.95468+01:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 367b213557f4ddb739ca7713087d37e69a462b13949f5334c582407f785839a8
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.12.5.tgz
    version: 4.12.5
  - annotations:
      artifacthub.io/changes: |
        - Update Ingress-Nginx version controller-v1.12.4
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.12.4
    created: "2025-12-05T08:20:46.947497+01:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 3fd191dcf815ec471101fdd725d437defcd4446a2681cf30b6095e4b46aa98aa
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.12.4.tgz
    version: 4.12.4
  - annotations:
      artifacthub.io/changes: |
        - Update Ingress-Nginx version controller-v1.12.3
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.12.3
    created: "2025-12-05T08:20:46.940958+01:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 0992603193d1c6f521fd3c2c8519d61b393656c3fa970cf8f7ab18a5ff0ed9f2
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.12.3.tgz
    version: 4.12.3
  - annotations:
      artifacthub.io/changes: |
        - Update Ingress-Nginx version controller-v1.12.2
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.12.2
    created: "2025-12-05T08:20:46.933105+01:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: 2dbeec3052a3744762131a7c042f242b834f50fe773591a502dacea38b64a319
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - ingress-nginx-4.12.2.tgz
    version: 4.12.2
generated: "2025-12-05T08:20:46.925448+01:00"
