apiVersion: v1
entries:
  cert-manager-webhook-pdns:
  - apiVersion: v2
    appVersion: v2.5.2
    created: "2025-12-06T10:28:18.807532+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: 0eec92ae5f781f7097b985d9f7e92ec84c07ef93d061ff74e245bfe60b635b7c
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-3.2.3.tgz
    version: 3.2.3
  - apiVersion: v2
    appVersion: v2.5.1
    created: "2025-12-06T10:28:18.807029+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: dbcfadc91d58b8389886f6eb5af69ed5467276a909352348570aa847aab6b8b4
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-3.2.2.tgz
    version: 3.2.2
  - apiVersion: v2
    appVersion: v2.5.1
    created: "2025-12-06T10:28:18.806517+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: 1852880ee102ddabf471724a1ac2fb3c66c6a3857fd274cb06fb513c123344a0
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-3.2.1.tgz
    version: 3.2.1
  - apiVersion: v2
    appVersion: v2.5.1
    created: "2025-12-06T10:28:18.806114+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: c594d3f13e2f66270728279d88c13e9c47d1c043525956a8127687052ae5cd22
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-3.2.0.tgz
    version: 3.2.0
  - apiVersion: v2
    appVersion: v2.5.1
    created: "2025-12-06T10:28:18.805743+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: 4b376353c6c4889a6556053e8484b432aa6beb9aa373da127700ccf96361590d
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-3.1.3.tgz
    version: 3.1.3
  - apiVersion: v2
    appVersion: v2.5.0
    created: "2025-12-06T10:28:18.805385+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: 47a976d972330690227419375efc5e8de5b4365d827a1b510d562ab4c7f76009
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-3.1.2.tgz
    version: 3.1.2
  - apiVersion: v2
    appVersion: v2.4.0
    created: "2025-12-06T10:28:18.805091+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: 146ae6fdd5cfac86ea5804746d52632208a86cc0a57b1c64b446b4b92803032a
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-3.1.1.tgz
    version: 3.1.1
  - apiVersion: v2
    appVersion: v2.3.0
    created: "2025-12-06T10:28:18.804502+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: 023dd00a025ce6d5624c847704cec51d8ca013dfac2fb27eac80b05cf797bd42
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-3.1.0.tgz
    version: 3.1.0
  - apiVersion: v2
    appVersion: v2.2.0
    created: "2025-12-06T10:28:18.803802+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: 27b0ca06c1e3da7828d9e11eef837f79c507f5fcdea05f77c9ed35e6969afc94
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-3.0.0.tgz
    version: 3.0.0
  - apiVersion: v2
    appVersion: v2.2.0
    created: "2025-12-06T10:28:18.803386+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: 1dfdca4636f3e64ef662ace2180d33ad69a3aa5deb0a0975c1994320d9027bb9
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v2
    appVersion: v2.2.0
    created: "2025-12-06T10:28:18.802982+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: 35ac0b57cb80810ddea6d29928119b2c9967944dc0ab3677097abb31a62c28cb
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-2.1.3.tgz
    version: 2.1.3
  - apiVersion: v2
    appVersion: v2.1.1
    created: "2025-12-06T10:28:18.802536+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: 51c555aaa418410b77a4e552a94982507639136c653886ed53abab52f8e83c6b
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-2.1.2.tgz
    version: 2.1.2
  - apiVersion: v2
    appVersion: v2.1.0
    created: "2025-12-06T10:28:18.802157+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: bf2a9b10d15dfc175ac3ce646da3f4d7f0315b3b78223513a5ebc37cd4774041
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-2.1.1.tgz
    version: 2.1.1
  - apiVersion: v2
    appVersion: v2.0.1
    created: "2025-12-06T10:28:18.801717+01:00"
    description: Cert Manager Webhook for PowerDNS.
    digest: 0958781367ede9f7fef7ddeb21357cb22722f82642264020a0e89f82da6773c9
    home: https://github.com/zachomedia/cert-manager-webhook-pdns
    maintainers:
    - email: zachary@zacharyseguin.ca
      name: Zachary Seguin
      url: https://zacharyseguin.ca
    name: cert-manager-webhook-pdns
    type: application
    urls:
    - cert-manager-webhook-pdns-2.1.0.tgz
    version: 2.1.0
generated: "2025-12-06T10:28:18.80112+01:00"
