apiVersion: v1
entries:
  vcluster:
  - apiVersion: v2
    appVersion: 0.25.1
    created: "2025-11-03T20:27:10.22363+01:00"
    description: vcluster - Virtual Kubernetes Clusters
    digest: bd0375fab6c2cf66646686cf1eb127a2edf2ae19c213b792f8f42ac92a477267
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-0.25.1.tgz
    version: 0.25.1
  - apiVersion: v2
    appVersion: 0.25.0
    created: "2025-11-03T20:27:10.22129+01:00"
    description: vcluster - Virtual Kubernetes Clusters
    digest: f7fc7784d34d8ba1ac7318c1f3c82086fac88930e2e73c745b77fa2cb74f6ce6
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-0.25.0.tgz
    version: 0.25.0
  - apiVersion: v2
    appVersion: 0.24.2
    created: "2025-11-03T20:27:10.219043+01:00"
    description: vcluster - Virtual Kubernetes Clusters
    digest: 69c018e75f90d14e2307030599f4c86f350c15fbce03645d39d426924d3c06da
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-0.24.2.tgz
    version: 0.24.2
  - apiVersion: v2
    appVersion: 0.24.1
    created: "2025-11-03T20:27:10.21664+01:00"
    description: vcluster - Virtual Kubernetes Clusters
    digest: 3300779bdc31bb02888fe5f5d1828f9db5b37754e6f1bf659a0aa94a1eb88b4c
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-0.24.1.tgz
    version: 0.24.1
  - apiVersion: v2
    appVersion: 0.24.0
    created: "2025-11-03T20:27:10.214575+01:00"
    description: vcluster - Virtual Kubernetes Clusters
    digest: f7e9f442e12019085abb9c89fd7aff61633508e2c8e1f9e8689e85e3d49686c5
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-0.24.0.tgz
    version: 0.24.0
  - apiVersion: v2
    appVersion: 0.23.2
    created: "2025-11-03T20:27:10.211999+01:00"
    description: vcluster - Virtual Kubernetes Clusters
    digest: dcc9ec9c238c394dc5115fe3ee79120b8995fa8daaf92a29da812a9c534e41da
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-0.23.2.tgz
    version: 0.23.2
  - apiVersion: v2
    appVersion: 0.23.1
    created: "2025-11-03T20:27:10.209653+01:00"
    description: vcluster - Virtual Kubernetes Clusters
    digest: 410f0c00dc571b969274f8ae34610793f4e7c4bb637fd613ad9a4824e7b8d9c4
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-0.23.1.tgz
    version: 0.23.1
  - apiVersion: v2
    appVersion: 0.23.0
    created: "2025-11-03T20:27:10.207358+01:00"
    description: vcluster - Virtual Kubernetes Clusters
    digest: e65875b1fd5ff6a2bc13259039f8cd62f2b6cc506e6f859b2d8bb334531196f8
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-0.23.0.tgz
    version: 0.23.0
  - apiVersion: v2
    appVersion: 0.22.6
    created: "2025-11-03T20:27:10.204784+01:00"
    description: vcluster - Virtual Kubernetes Clusters
    digest: 40b6499180c6c1949407aa2fd44ab73bed76e99de45c10d967ba26ebc8a6e7e6
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-0.22.6.tgz
    version: 0.22.6
  - apiVersion: v2
    appVersion: 0.22.5
    created: "2025-11-03T20:27:10.202856+01:00"
    description: vcluster - Virtual Kubernetes Clusters
    digest: cd1508c060ab20113de82139416e034d1271c578064a1900f0ac1bb87ea932f6
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-0.22.5.tgz
    version: 0.22.5
  - apiVersion: v2
    appVersion: 0.22.4
    created: "2025-11-03T20:27:10.200615+01:00"
    description: vcluster - Virtual Kubernetes Clusters
    digest: c2de8d1ec55c6f6472bfaa3f153d1e551606f49febabc23f620080c55f4d1d6d
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-0.22.4.tgz
    version: 0.22.4
  - apiVersion: v2
    appVersion: 0.22.3
    created: "2025-11-03T20:27:10.19865+01:00"
    description: vcluster - Virtual Kubernetes Clusters
    digest: 9f87cafb6ed441f345ed1a8ae97fae8d71858c63af786d880fed4be9fa84e388
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-0.22.3.tgz
    version: 0.22.3
  - apiVersion: v2
    appVersion: 0.22.2
    created: "2025-11-03T20:27:10.196305+01:00"
    description: vcluster - Virtual Kubernetes Clusters
    digest: 729f29455f420d96bdc65f2796d1a0f81b5dc37b84bef50e536782659f15becb
    home: https://vcluster.com
    icon: https://static.loft.sh/branding/logos/vcluster/vertical/vcluster_vertical.svg
    keywords:
    - developer
    - development
    - sharing
    - share
    - multi-tenancy
    - tenancy
    - cluster
    - space
    - namespace
    - vcluster
    - vclusters
    maintainers:
    - email: info@loft.sh
      name: Loft Labs, Inc.
      url: https://twitter.com/loft_sh
    name: vcluster
    sources:
    - https://github.com/loft-sh/vcluster
    type: application
    urls:
    - vcluster-0.22.2.tgz
    version: 0.22.2
generated: "2025-11-03T20:27:10.194084+01:00"
