apiVersion: v1
entries:
  valkey:
  - apiVersion: v2
    appVersion: 8.1.4
    created: "2025-11-03T20:27:11.958197+01:00"
    description: A Helm chart for Kubernetes
    digest: bb5e84239a8cf18d80cef40ad017961236cdf66e0e864a3a365b0f185b3727b1
    home: https://valkey.io/valkey-helm/
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
    maintainers:
    - name: raven
      url: https://github.com/mk-raven
    name: valkey
    sources:
    - https://github.com/valkey-io/valkey-helm.git
    - https://valkey.io
    type: application
    urls:
    - valkey-0.7.7.tgz
    version: 0.7.7
  - apiVersion: v2
    appVersion: 8.1.4
    created: "2025-11-03T20:27:11.957466+01:00"
    description: A Helm chart for Kubernetes
    digest: a158e267d620af5729ee36fa3c2d706fdb5df9633b77efcbc97dacd78d7d8178
    home: https://valkey.io/valkey-helm/
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
    maintainers:
    - name: raven
      url: https://github.com/mk-raven
    name: valkey
    sources:
    - https://github.com/valkey-io/valkey-helm.git
    - https://valkey.io
    type: application
    urls:
    - valkey-0.7.6.tgz
    version: 0.7.6
  - apiVersion: v2
    appVersion: 8.1.4
    created: "2025-11-03T20:27:11.956724+01:00"
    description: A Helm chart for Kubernetes
    digest: 59498dc029503081e00da9dd5e06b0dfddf20bf8a409438ab3ab4183ffbe01d8
    home: https://valkey.io/valkey-helm/
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
    maintainers:
    - name: raven
      url: https://github.com/mk-raven
    name: valkey
    sources:
    - https://github.com/valkey-io/valkey-helm.git
    - https://valkey.io
    type: application
    urls:
    - valkey-0.7.5.tgz
    version: 0.7.5
  - apiVersion: v2
    appVersion: 8.1.3
    created: "2025-11-03T20:27:11.956063+01:00"
    description: A Helm chart for Kubernetes
    digest: 88c5dd625cc0250bb888a4c8791a4abe4427ce8e69d02c22da1f117e66a4b9aa
    home: https://valkey.io/valkey-helm/
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
    maintainers:
    - name: raven
      url: https://github.com/mk-raven
    name: valkey
    sources:
    - https://github.com/valkey-io/valkey-helm.git
    - https://valkey.io
    type: application
    urls:
    - valkey-0.7.4.tgz
    version: 0.7.4
  - apiVersion: v2
    appVersion: 8.1.3
    created: "2025-11-03T20:27:11.955465+01:00"
    description: A Helm chart for Kubernetes
    digest: 314219ddea445f191faf6a14a980165b445261c5b003ba1e42e889457da3986e
    home: https://valkey.io/valkey-helm/
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
    maintainers:
    - name: raven
      url: https://github.com/mk-raven
    name: valkey
    sources:
    - https://github.com/valkey-io/valkey-helm.git
    - https://valkey.io
    type: application
    urls:
    - valkey-0.7.3.tgz
    version: 0.7.3
  - apiVersion: v2
    appVersion: 8.1.3
    created: "2025-11-03T20:27:11.954891+01:00"
    description: A Helm chart for Kubernetes
    digest: fd67b224f58eeec91f521039848ee2f0c8c463dfb0dec4eb65bf3b447c0ec4b4
    home: https://valkey.io/valkey-helm/
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
    maintainers:
    - name: raven
      url: https://github.com/mk-raven
    name: valkey
    sources:
    - https://github.com/valkey-io/valkey-helm.git
    - https://valkey.io
    type: application
    urls:
    - valkey-0.7.2.tgz
    version: 0.7.2
  - apiVersion: v2
    appVersion: 8.1.3
    created: "2025-11-03T20:27:11.954286+01:00"
    description: A Helm chart for Kubernetes
    digest: 406180b865ee5ba9b8cded0d0717127da3e1bc474b1ff824cbf9b50f0bcf528f
    home: https://github.com/mk-raven
    icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/valkey/img/valkey-stack-220x234.png
    maintainers:
    - name: raven
      url: https://github.com/mk-raven
    name: valkey
    sources:
    - https://github.com/mk-raven/valkey-helm.git
    - https://valkey.io
    type: application
    urls:
    - valkey-0.7.1.tgz
    version: 0.7.1
  - apiVersion: v2
    appVersion: 8.1.3
    created: "2025-11-03T20:27:11.953723+01:00"
    description: A Helm chart for Kubernetes
    digest: 30def2416d974076028b1f12ad109fb0621e647505feada318365ced92247a09
    home: https://github.com/mk-raven
    maintainers:
    - name: raven
      url: https://github.com/mk-raven
    name: valkey
    sources:
    - https://github.com/mk-raven/valkey-helm.git
    - https://valkey.io
    type: application
    urls:
    - valkey-0.7.0.tgz
    version: 0.7.0
  - apiVersion: v2
    appVersion: 8.1.3
    created: "2025-11-03T20:27:11.953066+01:00"
    description: A Helm chart for Kubernetes
    digest: 7a43dd032c3acb8c1612e2aef144fe5f552249c2b770402069f813325dba8e8d
    home: https://github.com/mk-raven
    maintainers:
    - name: raven
      url: https://github.com/mk-raven
    name: valkey
    sources:
    - https://github.com/mk-raven/valkey-helm.git
    - https://valkey.io
    type: application
    urls:
    - valkey-0.6.0.tgz
    version: 0.6.0
  - apiVersion: v2
    appVersion: 8.1.3
    created: "2025-11-03T20:27:11.95248+01:00"
    description: A Helm chart for Kubernetes
    digest: 378475cc1e4d039f5fd7339e5a9709ce99b8845e7cbdca37dc0c06ee9dc67c37
    home: https://github.com/mk-raven
    maintainers:
    - name: raven
      url: https://github.com/mk-raven
    name: valkey
    sources:
    - https://github.com/mk-raven/valkey-helm.git
    - https://valkey.io
    type: application
    urls:
    - valkey-0.5.1.tgz
    version: 0.5.1
  - apiVersion: v2
    appVersion: 8.1.0
    created: "2025-11-03T20:27:11.951754+01:00"
    description: A Helm chart for Kubernetes
    digest: 85f9bd37def8eec2e4b9c6007d7dc1a62ceeda778c6443d105e01eb8574e4072
    home: https://github.com/mk-raven
    maintainers:
    - name: raven
      url: https://github.com/mk-raven
    name: valkey
    sources:
    - https://github.com/mk-raven/valkey-helm.git
    - https://valkey.io
    type: application
    urls:
    - valkey-0.5.0.tgz
    version: 0.5.0
  - apiVersion: v2
    appVersion: 8.1.1
    created: "2025-11-03T20:27:11.950648+01:00"
    description: A Helm chart for Kubernetes
    digest: 9ced97956238b306db90907a1bb89e78e5c7e10aeaa93786d10a69042a875a65
    home: https://github.com/mk-raven
    maintainers:
    - name: raven
      url: https://github.com/mk-raven
    name: valkey
    sources:
    - https://github.com/mk-raven/valkey-helm.git
    - https://valkey.io
    type: application
    urls:
    - valkey-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 8.1.0
    created: "2025-11-03T20:27:11.949757+01:00"
    description: A Helm chart for Kubernetes
    digest: 780058b1b55b944c901a85cb78db063f905a96817545bb096e82e1fe28fb5a65
    home: https://github.com/mk-raven
    maintainers:
    - name: raven
      url: https://github.com/mk-raven
    name: valkey
    sources:
    - https://github.com/mk-raven/valkey-helm.git
    - https://valkey.io
    type: application
    urls:
    - valkey-0.3.0.tgz
    version: 0.3.0
generated: "2025-11-03T20:27:11.94889+01:00"
