apiVersion: v1
entries:
  metallb:
  - apiVersion: v2
    appVersion: v0.15.2
    created: "2025-11-08T00:24:48.715338+01:00"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.15.2
    - condition: frrk8s.enabled
      name: frr-k8s
      repository: https://metallb.github.io/frr-k8s
      version: 0.0.20
    description: A network load-balancer implementation for Kubernetes using standard
      routing protocols
    digest: 4f0fc313cd97819a1c78fff0a389dfe1c9f98bc490f33f521317475df1d7b873
    home: https://metallb.universe.tf
    icon: https://metallb.universe.tf/images/logo/metallb-white.png
    kubeVersion: '>= 1.19.0-0'
    name: metallb
    sources:
    - https://github.com/metallb/metallb
    type: application
    urls:
    - metallb-0.15.2.tgz
    version: 0.15.2
  - apiVersion: v2
    appVersion: v0.15.1
    created: "2025-11-08T00:24:48.713885+01:00"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.15.1
    - condition: frrk8s.enabled
      name: frr-k8s
      repository: https://metallb.github.io/frr-k8s
      version: 0.0.20
    description: A network load-balancer implementation for Kubernetes using standard
      routing protocols
    digest: 09e08918bb43d2454e22974209f7de3e63abd3372cde9ea18ab588d161e5b02c
    home: https://metallb.universe.tf
    icon: https://metallb.universe.tf/images/logo/metallb-white.png
    kubeVersion: '>= 1.19.0-0'
    name: metallb
    sources:
    - https://github.com/metallb/metallb
    type: application
    urls:
    - metallb-0.15.1.tgz
    version: 0.15.1
  - apiVersion: v2
    appVersion: v0.15.0
    created: "2025-11-08T00:24:48.712361+01:00"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.15.0
    - condition: frrk8s.enabled
      name: frr-k8s
      repository: https://metallb.github.io/frr-k8s
      version: 0.0.20
    description: A network load-balancer implementation for Kubernetes using standard
      routing protocols
    digest: d5ea9c1d4425cf494fddbfe14ce6887337433a61c3de75a52a147a8a3fa855a9
    home: https://metallb.universe.tf
    icon: https://metallb.universe.tf/images/logo/metallb-white.png
    kubeVersion: '>= 1.19.0-0'
    name: metallb
    sources:
    - https://github.com/metallb/metallb
    type: application
    urls:
    - metallb-0.15.0.tgz
    version: 0.15.0
  - apiVersion: v2
    appVersion: v0.14.9
    created: "2025-11-08T00:24:48.710507+01:00"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.14.9
    - condition: frrk8s.enabled
      name: frr-k8s
      repository: https://metallb.github.io/frr-k8s
      version: 0.0.16
    description: A network load-balancer implementation for Kubernetes using standard
      routing protocols
    digest: e808428c9047d0c218634bc0f7cc92b8545d4c207470b3b563cfcbb46ab31ae9
    home: https://metallb.universe.tf
    icon: https://metallb.universe.tf/images/logo/metallb-white.png
    kubeVersion: '>= 1.19.0-0'
    name: metallb
    sources:
    - https://github.com/metallb/metallb
    type: application
    urls:
    - metallb-0.14.9.tgz
    version: 0.14.9
  - apiVersion: v2
    appVersion: v0.14.8
    created: "2025-11-08T00:24:48.709021+01:00"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.14.8
    - condition: frrk8s.enabled
      name: frr-k8s
      repository: https://metallb.github.io/frr-k8s
      version: 0.0.14
    description: A network load-balancer implementation for Kubernetes using standard
      routing protocols
    digest: 9049735178558ce096e34eb723fa6d05d9efc8b275dcc1aa6f0f05cc8f905f8a
    home: https://metallb.universe.tf
    icon: https://metallb.universe.tf/images/logo/metallb-white.png
    kubeVersion: '>= 1.19.0-0'
    name: metallb
    sources:
    - https://github.com/metallb/metallb
    type: application
    urls:
    - metallb-0.14.8.tgz
    version: 0.14.8
  - apiVersion: v2
    appVersion: v0.14.7
    created: "2025-11-08T00:24:48.707578+01:00"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.14.7
    - condition: frrk8s.enabled
      name: frr-k8s
      repository: https://metallb.github.io/frr-k8s
      version: 0.0.13
    description: A network load-balancer implementation for Kubernetes using standard
      routing protocols
    digest: ae6cfa05f4475b6d7af78c2a2a7821db69f885a58c095c6c452f2779e1e34fed
    home: https://metallb.universe.tf
    icon: https://metallb.universe.tf/images/logo/metallb-white.png
    kubeVersion: '>= 1.19.0-0'
    name: metallb
    sources:
    - https://github.com/metallb/metallb
    type: application
    urls:
    - metallb-0.14.7.tgz
    version: 0.14.7
  - apiVersion: v2
    appVersion: v0.14.6
    created: "2025-11-08T00:24:48.706127+01:00"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.14.6
    - condition: frrk8s.enabled
      name: frr-k8s
      repository: https://metallb.github.io/frr-k8s
      version: 0.0.13
    description: A network load-balancer implementation for Kubernetes using standard
      routing protocols
    digest: f91dd8e75fe601451f4789d014bde078ba82ac21b9117a3b57a00cd9729345fa
    home: https://metallb.universe.tf
    icon: https://metallb.universe.tf/images/logo/metallb-white.png
    kubeVersion: '>= 1.19.0-0'
    name: metallb
    sources:
    - https://github.com/metallb/metallb
    type: application
    urls:
    - metallb-0.14.6.tgz
    version: 0.14.6
  - apiVersion: v2
    appVersion: v0.14.5
    created: "2025-11-08T00:24:48.704441+01:00"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.14.5
    - condition: frrk8s.enabled
      name: frr-k8s
      repository: https://metallb.github.io/frr-k8s
      version: 0.0.11
    description: A network load-balancer implementation for Kubernetes using standard
      routing protocols
    digest: 12e8d6a6ef2bf0d6450c10fba55c94282ef2d3559f78d2fbf626000d13baa9ef
    home: https://metallb.universe.tf
    icon: https://metallb.universe.tf/images/logo/metallb-white.png
    kubeVersion: '>= 1.19.0-0'
    name: metallb
    sources:
    - https://github.com/metallb/metallb
    type: application
    urls:
    - metallb-0.14.5.tgz
    version: 0.14.5
  - apiVersion: v2
    appVersion: v0.14.4
    created: "2025-11-08T00:24:48.702979+01:00"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.14.4
    - condition: frrk8s.enabled
      name: frr-k8s
      repository: https://metallb.github.io/frr-k8s
      version: 0.0.10
    description: A network load-balancer implementation for Kubernetes using standard
      routing protocols
    digest: 41c6026f19737cf3658df23d51023f924a510e8be619a733da38e7e4dc79d872
    home: https://metallb.universe.tf
    icon: https://metallb.universe.tf/images/logo/metallb-white.png
    kubeVersion: '>= 1.19.0-0'
    name: metallb
    sources:
    - https://github.com/metallb/metallb
    type: application
    urls:
    - metallb-0.14.4.tgz
    version: 0.14.4
  - apiVersion: v2
    appVersion: v0.14.3
    created: "2025-11-08T00:24:48.701522+01:00"
    dependencies:
    - condition: crds.enabled
      name: crds
      repository: ""
      version: 0.14.3
    - condition: frrk8s.enabled
      name: frr-k8s
      repository: https://metallb.github.io/frr-k8s
      version: 0.0.8
    description: A network load-balancer implementation for Kubernetes using standard
      routing protocols
    digest: 187adab54a96af4d8e7802f78921afad0866faef9afc53cf68628a745fec3833
    home: https://metallb.universe.tf
    icon: https://metallb.universe.tf/images/logo/metallb-white.png
    kubeVersion: '>= 1.19.0-0'
    name: metallb
    sources:
    - https://github.com/metallb/metallb
    type: application
    urls:
    - metallb-0.14.3.tgz
    version: 0.14.3
generated: "2025-11-08T00:24:48.699737+01:00"
