apiVersion: v1
entries:
  pgadmin:
  - apiVersion: v1
    appVersion: 4.13.0
    created: "2025-12-03T05:54:33.699441+01:00"
    description: pgAdmin is a web based administration tool for the PostgreSQL database.
    digest: 2e7a5826f6e7345d2c80b71e37182fd16fe2a7688e7fb8f110d511ab2925c0bb
    home: https://www.pgadmin.org/
    icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
    keywords:
    - pgadmin
    - postgres
    - database
    - sql
    maintainers:
    - name: alexnuttinck
    name: pgadmin
    urls:
    - pgadmin-0.1.12.tgz
    version: 0.1.12
  - apiVersion: v1
    appVersion: 4.13.0
    created: "2025-12-03T05:54:33.697601+01:00"
    description: pgAdmin is a web based administration tool for the PostgreSQL database.
    digest: c81f46c920fa516503a1ee82d8c7f56edfeaaaafc6b23d6ea82a8fd54a7e07cd
    home: https://www.pgadmin.org/
    icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
    keywords:
    - pgadmin
    - postgres
    - database
    - sql
    maintainers:
    - name: alexnuttinck
    name: pgadmin
    urls:
    - pgadmin-0.1.11.tgz
    version: 0.1.11
  - apiVersion: v1
    appVersion: 4.12.0
    created: "2025-12-03T05:54:33.695754+01:00"
    description: pgAdmin is a web based administration tool for the PostgreSQL database.
    digest: f57b78e286ab61588df22f34bb4250104b352c2bbc4b3dda59b581780dfa77c2
    home: https://www.pgadmin.org/
    icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
    keywords:
    - pgadmin
    - postgres
    - database
    - sql
    maintainers:
    - name: alexnuttinck
    name: pgadmin
    urls:
    - pgadmin-0.1.10.tgz
    version: 0.1.10
  - apiVersion: v1
    appVersion: 4.12.0
    created: "2025-12-03T05:54:33.711843+01:00"
    description: pgAdmin is a web based administration tool for the PostgreSQL database.
    digest: c5cdd5b97f3b77afe604016bd283ab7cbef9b663f404a0c6cc24d2f2ed7c178d
    home: https://www.pgadmin.org/
    icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
    keywords:
    - pgadmin
    - postgres
    - database
    - sql
    maintainers:
    - name: alexnuttinck
    name: pgadmin
    urls:
    - pgadmin-0.1.9.tgz
    version: 0.1.9
  - apiVersion: v1
    appVersion: 4.11.0
    created: "2025-12-03T05:54:33.710063+01:00"
    description: pgAdmin is a web based administration tool for the PostgreSQL database.
    digest: 12a8c60de7837e07c9a719a0b211986658918c8dae798c10240f5fbf99b5ea4b
    home: https://www.pgadmin.org/
    icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
    keywords:
    - pgadmin
    - postgres
    - database
    - sql
    maintainers:
    - name: alexnuttinck
    name: pgadmin
    urls:
    - pgadmin-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v1
    appVersion: 4.11.0
    created: "2025-12-03T05:54:33.708319+01:00"
    description: pgAdmin is a web based administration tool for the PostgreSQL database.
    digest: 56e845900aaf56964283958346fb4166c3a8c0219e808436b7a23499fc64c294
    home: https://www.pgadmin.org/
    icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
    keywords:
    - pgadmin
    - postgres
    - database
    - sql
    maintainers:
    - name: alexnuttinck
    name: pgadmin
    urls:
    - pgadmin-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v1
    appVersion: 4.11.0
    created: "2025-12-03T05:54:33.706824+01:00"
    description: pgAdmin is a web based administration tool for the PostgreSQL database.
    digest: 5be22030600194aee2e0294cae45efe481a1358ffce9724a86d30fe44b90fc4b
    home: https://www.pgadmin.org/
    icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
    keywords:
    - pgadmin
    - postgres
    - database
    - sql
    maintainers:
    - name: alexnuttinck
    name: pgadmin
    urls:
    - pgadmin-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v1
    appVersion: 4.11.0
    created: "2025-12-03T05:54:33.705113+01:00"
    description: pgAdmin is a web based administration tool for the PostgreSQL database.
    digest: a14e66a216fdf8e87d342cc54eb4f086d1cb04c986c5516b2f04a06c213599b1
    home: https://www.pgadmin.org/
    icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
    keywords:
    - pgadmin
    - postgres
    - database
    - sql
    maintainers:
    - name: alexnuttinck
    name: pgadmin
    urls:
    - pgadmin-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v1
    appVersion: 4.11.0
    created: "2025-12-03T05:54:33.702893+01:00"
    description: pgAdmin is a web based administration tool for the PostgreSQL database.
    digest: 0a55079b43826296d0bd8f6a417d5f6a722af2bafb290cec887d2c6fa44dda0a
    home: https://www.pgadmin.org/
    icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
    keywords:
    - pgadmin
    - postgres
    - database
    - sql
    maintainers:
    - name: alexnuttinck
    name: pgadmin
    urls:
    - pgadmin-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: 4.10.0
    created: "2025-12-03T05:54:33.70112+01:00"
    description: pgAdmin is a web based administration tool for the PostgreSQL database.
    digest: 80bd820dc9c1851888f22cdb175b17ca52c0b2758c38101a929e1761589f1d15
    home: https://www.pgadmin.org/
    icon: https://wiki.postgresql.org/images/3/30/PostgreSQL_logo.3colors.120x120.png
    keywords:
    - pgadmin
    - postgres
    - database
    - sql
    maintainers:
    - name: alexnuttinck
    name: pgadmin
    urls:
    - pgadmin-0.1.3.tgz
    version: 0.1.3
  phpldapadmin:
  - apiVersion: v1
    appVersion: 0.7.1
    created: "2025-12-03T05:54:33.716613+01:00"
    description: Web-based LDAP browser to manage your LDAP server
    digest: d148cc6965ae8b43ee341be3e29d9d5592a9153a0dac61f47dc476a7f228f9fe
    home: http://phpldapadmin.sourceforge.net
    icon: http://phpldapadmin.sourceforge.net/wiki/images/d/d4/Logo.jpg
    keywords:
    - phpldapadmin
    - openldap
    - userrights
    maintainers:
    - name: alexnuttinck
    - name: AyadiAmen
    name: phpldapadmin
    urls:
    - phpldapadmin-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: 0.7.1
    created: "2025-12-03T05:54:33.715045+01:00"
    description: Web-based LDAP browser to manage your LDAP server
    digest: e06a17b7ccc6e26391351b8ce39281a8d24ad8450878df665aba15df789f383b
    home: http://phpldapadmin.sourceforge.net
    icon: http://phpldapadmin.sourceforge.net/wiki/images/d/d4/Logo.jpg
    keywords:
    - phpldapadmin
    - openldap
    - userrights
    maintainers:
    - name: alexnuttinck
    - name: AyadiAmen
    name: phpldapadmin
    urls:
    - phpldapadmin-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v1
    appVersion: 0.7.1
    created: "2025-12-03T05:54:33.713545+01:00"
    description: Web-based LDAP browser to manage your LDAP server
    digest: 843bae8d6aa7f8a6a539b6fb7dd1c239a6855a5e2ecbb83bbfcdab0ab1375b97
    home: http://phpldapadmin.sourceforge.net
    icon: http://phpldapadmin.sourceforge.net/wiki/images/d/d4/Logo.jpg
    keywords:
    - phpldapadmin
    - openldap
    - userrights
    maintainers:
    - name: alexnuttinck
    - name: AyadiAmen
    name: phpldapadmin
    urls:
    - phpldapadmin-0.1.2.tgz
    version: 0.1.2
  postgresql:
  - apiVersion: v2
    appVersion: 11.5.0
    created: "2025-12-03T05:54:33.732979+01:00"
    description: PostgreSQL is an open-source object-relational database management
      system (ORDBMS) emphasizing extensibility and technical standards compliance.
    digest: c915562ca71e9db86a6f093d8a6489fa230307b89b8c68549297fa08d9e70470
    home: https://www.postgresql.org/
    icon: https://en.wikipedia.org/wiki/PostgreSQL#/media/File:Postgresql_elephant.svg
    keywords:
    - postgresql
    - postgres
    - database
    maintainers:
    - name: alexnuttinck
    - name: AyadiAmen
    name: postgresql
    urls:
    - postgresql-0.2.5.tgz
    version: 0.2.5
  - apiVersion: v2
    appVersion: 11.5.0
    created: "2025-12-03T05:54:33.731417+01:00"
    description: PostgreSQL is an open-source object-relational database management
      system (ORDBMS) emphasizing extensibility and technical standards compliance.
    digest: fdba5a143367a632d8d77520a919cb91031edb7eb15187334c518517f82c86a1
    home: https://www.postgresql.org/
    icon: https://en.wikipedia.org/wiki/PostgreSQL#/media/File:Postgresql_elephant.svg
    keywords:
    - postgresql
    - postgres
    - database
    maintainers:
    - name: alexnuttinck
    - name: AyadiAmen
    name: postgresql
    urls:
    - postgresql-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    appVersion: 11.5.0
    created: "2025-12-03T05:54:33.729935+01:00"
    description: PostgreSQL is an open-source object-relational database management
      system (ORDBMS) emphasizing extensibility and technical standards compliance.
    digest: 20fe1b238f163e78cc9f8ecdc7b2b160aa6bd6e7429349b7fff403688a009b1b
    home: https://www.postgresql.org/
    icon: https://en.wikipedia.org/wiki/PostgreSQL#/media/File:Postgresql_elephant.svg
    keywords:
    - postgresql
    - postgres
    - database
    maintainers:
    - name: alexnuttinck
    - name: AyadiAmen
    name: postgresql
    urls:
    - postgresql-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: 11.5.0
    created: "2025-12-03T05:54:33.728432+01:00"
    description: PostgreSQL is an open-source object-relational database management
      system (ORDBMS) emphasizing extensibility and technical standards compliance.
    digest: cb6ae437428e50eb51863f72201abf7f1c0d9168aba80fbe5e19e89821851eaf
    home: https://www.postgresql.org/
    icon: https://en.wikipedia.org/wiki/PostgreSQL#/media/File:Postgresql_elephant.svg
    keywords:
    - postgresql
    - postgres
    - database
    maintainers:
    - name: alexnuttinck
    - name: AyadiAmen
    name: postgresql
    urls:
    - postgresql-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 11.5.0
    created: "2025-12-03T05:54:33.726814+01:00"
    description: PostgreSQL is an open-source object-relational database management
      system (ORDBMS) emphasizing extensibility and technical standards compliance.
    digest: cde571f96755461d5be04803ecb1c4d52bb14da99118e1ff1c738608699208e5
    home: https://www.postgresql.org/
    icon: https://en.wikipedia.org/wiki/PostgreSQL#/media/File:Postgresql_elephant.svg
    keywords:
    - postgresql
    - postgres
    - database
    maintainers:
    - name: alexnuttinck
    - name: AyadiAmen
    name: postgresql
    urls:
    - postgresql-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: 11.5.0
    created: "2025-12-03T05:54:33.724871+01:00"
    description: PostgreSQL is an open-source object-relational database management
      system (ORDBMS) emphasizing extensibility and technical standards compliance.
    digest: 43b66b632786413fbb04c62f7b40ff70e669989a9c154657399a954e15ee3700
    home: https://www.postgresql.org/
    icon: https://en.wikipedia.org/wiki/PostgreSQL#/media/File:Postgresql_elephant.svg
    keywords:
    - postgresql
    - postgres
    - database
    maintainers:
    - name: alexnuttinck
    - name: AyadiAmen
    name: postgresql
    urls:
    - postgresql-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: 11.5.0
    created: "2025-12-03T05:54:33.723257+01:00"
    description: PostgreSQL is an open-source object-relational database management
      system (ORDBMS) emphasizing extensibility and technical standards compliance.
    digest: e80ef1a3bebe97ed4788c9b9e2db257ef289983e66c0147ee445df80433eca5b
    home: https://www.postgresql.org/
    icon: https://en.wikipedia.org/wiki/PostgreSQL#/media/File:Postgresql_elephant.svg
    keywords:
    - postgresql
    - postgres
    - database
    maintainers:
    - name: alexnuttinck
    - name: AyadiAmen
    name: postgresql
    urls:
    - postgresql-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v1
    appVersion: 11.5.0
    created: "2025-12-03T05:54:33.721607+01:00"
    description: PostgreSQL is an open-source object-relational database management
      system (ORDBMS) emphasizing extensibility and technical standards compliance.
    digest: 718f661adcb3e9a785c834dc99a03bab6036d48847c4d130c120ff4a681fc9d3
    home: https://www.postgresql.org/
    icon: https://en.wikipedia.org/wiki/PostgreSQL#/media/File:Postgresql_elephant.svg
    keywords:
    - postgresql
    - postgres
    - database
    maintainers:
    - name: alexnuttinck
    - name: AyadiAmen
    name: postgresql
    urls:
    - postgresql-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v1
    appVersion: 11.5.0
    created: "2025-12-03T05:54:33.720019+01:00"
    description: PostgreSQL is an open-source object-relational database management
      system (ORDBMS) emphasizing extensibility and technical standards compliance.
    digest: 6f12a8cd92193336fe82199a6be93b9f11f7d66fdabd7d089244177f113ed2df
    home: https://www.postgresql.org/
    icon: https://en.wikipedia.org/wiki/PostgreSQL#/media/File:Postgresql_elephant.svg
    keywords:
    - postgresql
    - postgres
    - database
    maintainers:
    - name: alexnuttinck
    - name: AyadiAmen
    name: postgresql
    urls:
    - postgresql-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    appVersion: 11.5.0
    created: "2025-12-03T05:54:33.718289+01:00"
    description: PostgreSQL is an open-source object-relational database management
      system (ORDBMS) emphasizing extensibility and technical standards compliance.
    digest: 5aa5cab02efea06106cf082073bce303c5b809c6c0e8f7596144c5c9c19dd942
    home: https://www.postgresql.org/
    icon: https://en.wikipedia.org/wiki/PostgreSQL#/media/File:Postgresql_elephant.svg
    keywords:
    - postgresql
    - postgres
    - database
    maintainers:
    - name: alexnuttinck
    - name: AyadiAmen
    name: postgresql
    urls:
    - postgresql-0.1.0.tgz
    version: 0.1.0
generated: "2025-12-03T05:54:33.693128+01:00"
