apiVersion: v1
entries:
  confluent-for-kubernetes:
  - apiVersion: v1
    appVersion: 3.1.0
    created: "2025-12-03T05:54:54.95861+01:00"
    description: A Helm chart to deploy Confluent for Kubernetes
    digest: 2b63bac011b19f3bfd7209fbfb046a57d53b33d96eb2e098fbc9179aaf45693a
    home: https://www.confluent.io/
    keywords:
    - Confluent
    - Confluent Operator
    - Confluent Platform
    - CFK
    maintainers:
    - email: operator@confluent.io
      name: Confluent Operator
    name: confluent-for-kubernetes
    sources:
    - https://docs.confluent.io/current/index.html
    urls:
    - confluent-for-kubernetes-0.1351.24.tgz
    version: 0.1351.24
  - apiVersion: v1
    appVersion: 3.0.1
    created: "2025-12-03T05:54:54.942574+01:00"
    description: A Helm chart to deploy Confluent for Kubernetes
    digest: e16075db026e54e55e2e2b3b58a679ea13ac949e8cdcec75f5fcb7a3c1f8b7ce
    home: https://www.confluent.io/
    keywords:
    - Confluent
    - Confluent Operator
    - Confluent Platform
    - CFK
    maintainers:
    - email: operator@confluent.io
      name: Confluent Operator
    name: confluent-for-kubernetes
    sources:
    - https://docs.confluent.io/current/index.html
    urls:
    - confluent-for-kubernetes-0.1263.34.tgz
    version: 0.1263.34
  - apiVersion: v1
    appVersion: 3.0.0
    created: "2025-12-03T05:54:54.950993+01:00"
    description: A Helm chart to deploy Confluent for Kubernetes
    digest: 9a966ce4b9fc08e22c932918a341ddfac46d0a1dce23b2bbec9c70a292196416
    home: https://www.confluent.io/
    keywords:
    - Confluent
    - Confluent Operator
    - Confluent Platform
    - CFK
    maintainers:
    - email: operator@confluent.io
      name: Confluent Operator
    name: confluent-for-kubernetes
    sources:
    - https://docs.confluent.io/current/index.html
    urls:
    - confluent-for-kubernetes-0.1263.8.tgz
    version: 0.1263.8
  - apiVersion: v1
    appVersion: 2.11.3
    created: "2025-12-03T05:54:54.93292+01:00"
    description: A Helm chart to deploy Confluent for Kubernetes
    digest: 03c7cd60d6e192abf65ed73e41bf1671d6b38e455161f20c2b7b6d8d1c81acd4
    home: https://www.confluent.io/
    keywords:
    - Confluent
    - Confluent Operator
    - Confluent Platform
    - CFK
    maintainers:
    - email: operator@confluent.io
      name: Confluent Operator
    name: confluent-for-kubernetes
    sources:
    - https://docs.confluent.io/current/index.html
    urls:
    - confluent-for-kubernetes-0.1193.70.tgz
    version: 0.1193.70
  - apiVersion: v1
    appVersion: 2.11.2
    created: "2025-12-03T05:54:54.917586+01:00"
    description: A Helm chart to deploy Confluent for Kubernetes
    digest: 9b7da5e6f49f3c6ee3ba8ea54d5867e9e7e1232a5c88c390b0be63182b5223ef
    home: https://www.confluent.io/
    keywords:
    - Confluent
    - Confluent Operator
    - Confluent Platform
    - CFK
    maintainers:
    - email: operator@confluent.io
      name: Confluent Operator
    name: confluent-for-kubernetes
    sources:
    - https://docs.confluent.io/current/index.html
    urls:
    - confluent-for-kubernetes-0.1193.47.tgz
    version: 0.1193.47
  - apiVersion: v1
    appVersion: 2.11.1
    created: "2025-12-03T05:54:54.902168+01:00"
    description: A Helm chart to deploy Confluent for Kubernetes
    digest: 990eb79eebac1c9a6f2abf5a86edc776f0d54cfa8a0052a40ac53eb34089553e
    home: https://www.confluent.io/
    keywords:
    - Confluent
    - Confluent Operator
    - Confluent Platform
    - CFK
    maintainers:
    - email: operator@confluent.io
      name: Confluent Operator
    name: confluent-for-kubernetes
    sources:
    - https://docs.confluent.io/current/index.html
    urls:
    - confluent-for-kubernetes-0.1193.34.tgz
    version: 0.1193.34
  - apiVersion: v1
    appVersion: 2.11.0
    created: "2025-12-03T05:54:54.887379+01:00"
    description: A Helm chart to deploy Confluent for Kubernetes
    digest: 74c41db110eef69b774f7051e6f02879703ffb2821b0ef5a44333a0c7f66099f
    home: https://www.confluent.io/
    keywords:
    - Confluent
    - Confluent Operator
    - Confluent Platform
    - CFK
    maintainers:
    - email: operator@confluent.io
      name: Confluent Operator
    name: confluent-for-kubernetes
    sources:
    - https://docs.confluent.io/current/index.html
    urls:
    - confluent-for-kubernetes-0.1193.1.tgz
    version: 0.1193.1
  - apiVersion: v1
    appVersion: 2.10.3
    created: "2025-12-03T05:54:54.8729+01:00"
    description: A Helm chart to deploy Confluent for Kubernetes
    digest: 320479f347b2970fb1c6b470c4734af7eab81207fa8160f175056317e316b139
    home: https://www.confluent.io/
    keywords:
    - Confluent
    - Confluent Operator
    - Confluent Platform
    - CFK
    maintainers:
    - email: operator@confluent.io
      name: Confluent Operator
    name: confluent-for-kubernetes
    sources:
    - https://docs.confluent.io/current/index.html
    urls:
    - confluent-for-kubernetes-0.1145.71.tgz
    version: 0.1145.71
  - apiVersion: v1
    appVersion: 2.10.2
    created: "2025-12-03T05:54:54.844566+01:00"
    description: A Helm chart to deploy Confluent for Kubernetes
    digest: 723d2f6fea5ae32b0376287c10d60c2848e627ecf248abe5d6b23c1607e664cd
    home: https://www.confluent.io/
    keywords:
    - Confluent
    - Confluent Operator
    - Confluent Platform
    - CFK
    maintainers:
    - email: operator@confluent.io
      name: Confluent Operator
    name: confluent-for-kubernetes
    sources:
    - https://docs.confluent.io/current/index.html
    urls:
    - confluent-for-kubernetes-0.1145.50.tgz
    version: 0.1145.50
  - apiVersion: v1
    appVersion: 2.10.1
    created: "2025-12-03T05:54:54.82877+01:00"
    description: A Helm chart to deploy Confluent for Kubernetes
    digest: dd2717eadcf066444ee47b11776a011974fde7df04dca9c6128ee49fa424cad6
    home: https://www.confluent.io/
    keywords:
    - Confluent
    - Confluent Operator
    - Confluent Platform
    - CFK
    maintainers:
    - email: operator@confluent.io
      name: Confluent Operator
    name: confluent-for-kubernetes
    sources:
    - https://docs.confluent.io/current/index.html
    urls:
    - confluent-for-kubernetes-0.1145.35.tgz
    version: 0.1145.35
  - apiVersion: v1
    appVersion: 2.10.0
    created: "2025-12-03T05:54:54.858165+01:00"
    description: A Helm chart to deploy Confluent for Kubernetes
    digest: 2942cac0588d236347ee624a08e1ce94d68cfbb4d7a54b0b78fd151e91a65a2f
    home: https://www.confluent.io/
    keywords:
    - Confluent
    - Confluent Operator
    - Confluent Platform
    - CFK
    maintainers:
    - email: operator@confluent.io
      name: Confluent Operator
    name: confluent-for-kubernetes
    sources:
    - https://docs.confluent.io/current/index.html
    urls:
    - confluent-for-kubernetes-0.1145.6.tgz
    version: 0.1145.6
generated: "2025-12-03T05:54:54.812018+01:00"
