apiVersion: v1
entries:
  raw:
  - apiVersion: v1
    appVersion: 0.2.3
    created: "2025-11-12T19:50:05.668771+01:00"
    deprecated: true
    description: DEPRECATED A place for all the Kubernetes resources which don't already
      have a home.
    digest: 56b3e35a6567e0f335e703bf6802edd3e8c9b065fc8d9d58305c98c2ca81970d
    home: https://github.com/helm/charts/blob/master/incubator/raw
    name: raw
    urls:
    - raw-0.2.5.tgz
    version: 0.2.5
  - apiVersion: v1
    appVersion: 0.2.3
    created: "2025-11-12T19:50:05.668391+01:00"
    description: A place for all the Kubernetes resources which don't already have
      a home.
    digest: e67e182ed94a6275632b01d0381b4776e063879251719010c537b8e2a38d0c35
    home: https://github.com/helm/charts/blob/master/incubator/raw
    maintainers:
    - email: josdotso@cisco.com
      name: josdotso
    - email: ykuoka@gmail.com
      name: mumoshu
    name: raw
    urls:
    - raw-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v1
    appVersion: 0.2.3
    created: "2025-11-12T19:50:05.668084+01:00"
    description: A place for all the Kubernetes resources which don't already have
      a home.
    digest: b441b2f3b445f7e352ba56714d05fed0f53adea458dbe01fe1cfe1f16d4092a1
    home: https://github.com/helm/charts/blob/master/incubator/raw
    maintainers:
    - email: josdotso@cisco.com
      name: josdotso
    - email: ykuoka@gmail.com
      name: mumoshu
    name: raw
    urls:
    - raw-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v1
    appVersion: 0.2.1
    created: "2025-11-12T19:50:05.667759+01:00"
    description: A place for all the Kubernetes resources which don't already have
      a home.
    digest: b9347ef20ef7021237dbb4c33e887b527cf066ec845227a47199cf30a14c8bab
    home: https://github.com/helm/charts/blob/master/incubator/raw
    maintainers:
    - email: josdotso@cisco.com
      name: josdotso
    - email: ykuoka@gmail.com
      name: mumoshu
    name: raw
    urls:
    - raw-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v1
    appVersion: 0.2.1
    created: "2025-11-12T19:50:05.667264+01:00"
    description: A place for all the Kubernetes resources which don't already have
      a home.
    digest: abadc5ffb0e1b84ad74d8ebade1cdf617ca0162c1abe21026848903b9d49e252
    home: https://github.com/helm/charts/blob/master/incubator/raw
    maintainers:
    - email: josdotso@cisco.com
      name: josdotso
    - email: ykuoka@gmail.com
      name: mumoshu
    name: raw
    urls:
    - raw-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v1
    appVersion: 0.2.0
    created: "2025-11-12T19:50:05.666974+01:00"
    description: A place for all the Kubernetes resources which don't already have
      a home.
    digest: 6c79e6d69aa8110f2fa80e664f7bdfd5fd6147315e83b84eb2f11c74ccbb7b12
    home: https://github.com/helm/charts/blob/master/incubator/raw
    maintainers:
    - email: josdotso@cisco.com
      name: josdotso
    - email: ykuoka@gmail.com
      name: mumoshu
    name: raw
    urls:
    - raw-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    appVersion: 0.1.0
    created: "2025-11-12T19:50:05.66647+01:00"
    description: A place for all the Kubernetes resources which don't already have
      a home.
    digest: d0d470ba061da4aaa071623d9cd8b63cdeced429948cc4635338fda32a15aecf
    home: https://github.com/helm/charts/blob/master/incubator/raw
    maintainers:
    - email: josdotso@cisco.com
      name: josdotso
    name: raw
    urls:
    - raw-0.1.0.tgz
    version: 0.1.0
generated: "2025-11-12T19:50:05.665783+01:00"
