apiVersion: v1
entries:
  minio:
  - apiVersion: v1
    appVersion: RELEASE.2024-12-18T13-15-44Z
    created: "2025-11-26T19:43:08.79539+01:00"
    description: High Performance Object Storage
    digest: 25fa2740480d1ebc9e64340854a6c42d3a7bc39c2a77378da91b21f144faa9af
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - minio-5.4.0.tgz
    version: 5.4.0
  - apiVersion: v1
    appVersion: RELEASE.2024-04-18T19-09-19Z
    created: "2025-11-26T19:43:08.794221+01:00"
    description: High Performance Object Storage
    digest: 5f927286767c285b925a3395e75b4f372367f83d2124395185e21dc7fd4ca177
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - minio-5.3.0.tgz
    version: 5.3.0
  - apiVersion: v1
    appVersion: RELEASE.2024-04-18T19-09-19Z
    created: "2025-11-26T19:43:08.793197+01:00"
    description: High Performance Object Storage
    digest: 8ef4212d7d51be6c8192b3e91138a9ca918ca56142c42500028cfd3b80e0b2dd
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - minio-5.2.0.tgz
    version: 5.2.0
  - apiVersion: v1
    appVersion: RELEASE.2024-03-03T17-50-39Z
    created: "2025-11-26T19:43:08.792193+01:00"
    description: High Performance Object Storage
    digest: 742d658c029616f0a977f255a27e806f2e3ef31f0d30467353a0882b5607001e
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - minio-5.1.0.tgz
    version: 5.1.0
  - apiVersion: v1
    appVersion: RELEASE.2024-01-11T07-46-16Z
    created: "2025-11-26T19:43:08.7908+01:00"
    description: Multi-Cloud Object Storage
    digest: 3a2d8e03ffdd98501026aa7561633c91d9871647f4b01d77b75a2ad9b72ee618
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - minio-5.0.15.tgz
    version: 5.0.15
  - apiVersion: v1
    appVersion: RELEASE.2023-09-30T07-02-29Z
    created: "2025-11-26T19:43:08.789765+01:00"
    description: Multi-Cloud Object Storage
    digest: 6c3656924fbad2cb17f810cd78f352f9b60626aaec64b837c96829095b215ad3
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - minio-5.0.14.tgz
    version: 5.0.14
  - apiVersion: v1
    appVersion: RELEASE.2023-07-07T07-13-57Z
    created: "2025-11-26T19:43:08.788801+01:00"
    description: Multi-Cloud Object Storage
    digest: 3c18f7381efe6d86497f952e6d5f59003ee5a009c54778ddea1ee8d3c7bed9c8
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - minio-5.0.13.tgz
    version: 5.0.13
  - apiVersion: v1
    appVersion: RELEASE.2023-07-07T07-13-57Z
    created: "2025-11-26T19:43:08.787895+01:00"
    description: Multi-Cloud Object Storage
    digest: 5318bc56c73a8f4539c3dd178f4d55c7f41bee4a25d7dc02ac6a5843eeee7976
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - minio-5.0.12.tgz
    version: 5.0.12
  - apiVersion: v1
    appVersion: RELEASE.2023-06-19T19-52-50Z
    created: "2025-11-26T19:43:08.786862+01:00"
    description: Multi-Cloud Object Storage
    digest: cba44c8cddcda1fb5c082dce82004a39f53cc20677ab9698a6998f01efefd8db
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - minio-5.0.11.tgz
    version: 5.0.11
  - apiVersion: v1
    appVersion: RELEASE.2023-05-18T00-05-36Z
    created: "2025-11-26T19:43:08.785632+01:00"
    description: Multi-Cloud Object Storage
    digest: a3d55b12f38a2049ddf3efe35b38b6dc4e59777452b72d18d5a82f3378deb9cd
    home: https://min.io
    icon: https://min.io/resources/img/logo/MINIO_wordmark.png
    keywords:
    - minio
    - storage
    - object-storage
    - s3
    - cluster
    maintainers:
    - email: dev@minio.io
      name: MinIO, Inc
    name: minio
    sources:
    - https://github.com/minio/minio
    urls:
    - minio-5.0.10.tgz
    version: 5.0.10
generated: "2025-11-26T19:43:08.784544+01:00"
